import type { SiteConfig } from "@injury/schema";

export const siteConfig: SiteConfig = {
  city: "Denver",
  state: "Colorado",
  stateAbbr: "CO",
  siteName: "Denver Injury Law Group",
  domain: "devnercoloradoinjurylawyer.com",
  phone: "(720) 740-5474",
  phoneFormatted: "(720) 740-5474",
  lawyerName: "[Placeholder Attorney]",
  firmName: "Denver Injury Law Group",
  address: "1700 Lincoln St, Suite 2000, Denver, CO 80203",
  addressStreet: "1700 Lincoln St, Suite 2000",
  addressCity: "Denver",
  addressState: "Colorado",
  addressZip: "80203",
  email: "contact@devnercoloradoinjurylawyer.com",
  hours: "Monday–Friday 8am–8pm, Saturday 9am–5pm, Sunday Emergency Only",
  latitude: "39.7392",
  longitude: "-104.9903",
  googleMapsUrl: "https://maps.google.com/?q=1700+Lincoln+St+Denver+CO",
  lawyerPhoto: "/images/attorney.jpg",
  description:
    "Aggressive personal injury attorneys serving Denver, Aurora, Lakewood, Arvada, and all of Metro Denver. No fee unless we win.",
  tagline: "Denver's Most Aggressive Injury Lawyers",
  elevenLabsAgentId: "", // will be filled in after creating the agent
  serviceAreas: [
    { label: "Aurora", slug: "aurora" },
    { label: "Lakewood", slug: "lakewood" },
    { label: "Arvada", slug: "arvada" },
    { label: "Westminster", slug: "westminster" },
    { label: "Thornton", slug: "thornton" },
    { label: "Centennial", slug: "centennial" },
    { label: "Highlands Ranch", slug: "highlands-ranch" },
    { label: "Englewood", slug: "englewood" },
    { label: "Littleton", slug: "littleton" },
    { label: "Commerce City", slug: "commerce-city" },
    { label: "Parker", slug: "parker" },
    { label: "Brighton", slug: "brighton" },
    { label: "Boulder", slug: "boulder" },
    { label: "Broomfield", slug: "broomfield" },
    { label: "Castle Rock", slug: "castle-rock" },
  ],
};
