import type { SiteConfig } from "@injury/schema";

export const siteConfig: SiteConfig = {
  city: "Omaha",
  state: "Nebraska",
  stateAbbr: "NE",
  siteName: "Omaha Injury Law Group",
  domain: "omahanebraskainjurylawyer.com",
  phone: "(402) 555-0167",
  phoneFormatted: "(402) 555-0167",
  lawyerName: "[Placeholder Attorney]",
  firmName: "Omaha Injury Law Group",
  address: "1299 Farnam St, Suite 300, Omaha, NE 68102",
  addressStreet: "1299 Farnam St, Suite 300",
  addressCity: "Omaha",
  addressState: "Nebraska",
  addressZip: "68102",
  email: "contact@omahanebraskainjurylawyer.com",
  hours: "Monday–Friday 8am–8pm, Saturday 9am–5pm, Sunday Emergency Only",
  latitude: "41.2565",
  longitude: "-95.9345",
  googleMapsUrl: "https://maps.google.com/?q=1299+Farnam+St+Omaha+NE",
  lawyerPhoto: "/images/attorney.jpg",
  description:
    "Aggressive personal injury attorneys serving Omaha, Bellevue, Papillion, La Vista, and all of Eastern Nebraska. No fee unless we win.",
  tagline: "Omaha's Most Aggressive Injury Lawyers",
  elevenLabsAgentId: "agent_7201krfrw0eqfqsrsq63cxnwcedf",
  serviceAreas: [
    { label: "Bellevue", slug: "bellevue" },
    { label: "Papillion", slug: "papillion" },
    { label: "La Vista", slug: "la-vista" },
    { label: "Elkhorn", slug: "elkhorn" },
    { label: "Millard", slug: "millard" },
    { label: "Midtown", slug: "midtown" },
    { label: "South Omaha", slug: "south-omaha" },
    { label: "North Omaha", slug: "north-omaha" },
    { label: "Council Bluffs", slug: "council-bluffs" },
    { label: "Dundee", slug: "dundee" },
    { label: "Benson", slug: "benson" },
    { label: "Ralston", slug: "ralston" },
    { label: "Boys Town", slug: "boys-town" },
    { label: "Chalco", slug: "chalco" },
    { label: "Aksarben", slug: "aksarben" },
  ],
};
