import type { SiteConfig } from "@injury/schema";

export const siteConfig: SiteConfig = {
  city: "Dallas",
  state: "Texas",
  stateAbbr: "TX",
  siteName: "Dallas Injury Law Group",
  domain: "dallastexasinjurylawyer.com",
  phone: "(469) 837-7919",
  phoneFormatted: "(469) 837-7919",
  lawyerName: "[Placeholder Attorney]",
  firmName: "Dallas Injury Law Group",
  address: "1601 Elm St, Suite 3000, Dallas, TX 75201",
  addressStreet: "1601 Elm St, Suite 3000",
  addressCity: "Dallas",
  addressState: "Texas",
  addressZip: "75201",
  email: "contact@dallastexasinjurylawyer.com",
  hours: "Monday–Friday 8am–8pm, Saturday 9am–5pm, Sunday Emergency Only",
  latitude: "32.7767",
  longitude: "-96.7970",
  googleMapsUrl: "https://maps.google.com/?q=1601+Elm+St+Dallas+TX",
  lawyerPhoto: "/images/attorney.jpg",
  description:
    "Aggressive personal injury attorneys serving Dallas, Plano, Irving, Arlington, and all of DFW. No fee unless we win.",
  tagline: "Dallas's Most Aggressive Injury Lawyers",
  elevenLabsAgentId: "agent_2601krfrvrqxe1rt4mhpex3n5whp",
  serviceAreas: [
    { label: "Downtown Dallas", slug: "downtown-dallas" },
    { label: "Uptown", slug: "uptown" },
    { label: "Oak Cliff", slug: "oak-cliff" },
    { label: "Plano", slug: "plano" },
    { label: "Irving", slug: "irving" },
    { label: "Arlington", slug: "arlington" },
    { label: "Garland", slug: "garland" },
    { label: "Mesquite", slug: "mesquite" },
    { label: "Frisco", slug: "frisco" },
    { label: "McKinney", slug: "mckinney" },
    { label: "Richardson", slug: "richardson" },
    { label: "Grand Prairie", slug: "grand-prairie" },
    { label: "Denton", slug: "denton" },
    { label: "Carrollton", slug: "carrollton" },
    { label: "Lewisville", slug: "lewisville" },
  ],
};
