import type { SiteConfig } from "@injury/schema";

export const siteConfig: SiteConfig = {
  city: "Austin",
  state: "Texas",
  stateAbbr: "TX",
  siteName: "Austin Injury Law Group",
  domain: "austintexasinjurylawyer.com",
  phone: "(512) 948-3458",
  phoneFormatted: "(512) 948-3458",
  lawyerName: "[Placeholder Attorney]",
  firmName: "Austin Injury Law Group",
  address: "301 Congress Ave, Suite 1400, Austin, TX 78701",
  addressStreet: "301 Congress Ave, Suite 1400",
  addressCity: "Austin",
  addressState: "Texas",
  addressZip: "78701",
  email: "contact@austintexasinjurylawyer.com",
  hours: "Monday–Friday 8am–8pm, Saturday 9am–5pm, Sunday Emergency Only",
  latitude: "30.2672",
  longitude: "-97.7431",
  googleMapsUrl: "https://maps.google.com/?q=301+Congress+Ave+Austin+TX",
  lawyerPhoto: "/images/attorney.jpg",
  description:
    "Aggressive personal injury attorneys serving Austin, Round Rock, Cedar Park, Georgetown, and all of Central Texas. No fee unless we win.",
  tagline: "Austin's Most Aggressive Injury Lawyers",
  elevenLabsAgentId: "agent_3101krfrvwwxfgm9anxt1xbwhg4v",
  serviceAreas: [
    { label: "Round Rock", slug: "round-rock" },
    { label: "Cedar Park", slug: "cedar-park" },
    { label: "Georgetown", slug: "georgetown" },
    { label: "Kyle", slug: "kyle" },
    { label: "Pflugerville", slug: "pflugerville" },
    { label: "Leander", slug: "leander" },
    { label: "Buda", slug: "buda" },
    { label: "San Marcos", slug: "san-marcos" },
    { label: "Hutto", slug: "hutto" },
    { label: "Taylor", slug: "taylor" },
    { label: "Lakeway", slug: "lakeway" },
    { label: "Dripping Springs", slug: "dripping-springs" },
    { label: "Bastrop", slug: "bastrop" },
    { label: "Manor", slug: "manor" },
    { label: "Westlake", slug: "westlake" },
  ],
};
